# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            'Machine Learning'
tagline:          'Documentation on me learning ML'
description:      ''
url:              http://ponte-vecchio.github.io/machinelearning/
baseurl:          http://ponte-vecchio.github.io/machinelearning/

author:
  name:           'Jevgeni Khaganov'
  url:            https://gitlab.paradoxical.pw/ponte-vecchio

paginate:         1
