# Dependencies
theme:            jekyll-theme-minimal

# Setup
url:              http://ponte-vecchio.github.io/machinelearning/
baseurl:          http://ponte-vecchio.github.io/machinelearning/

author:
  name:           'Jevgeni Khaganov'
  url:            https://gitlab.paradoxical.pw/ponte-vecchio
